### ISSUE TITLE
pod is stuck on a "bootloop"

### ISSUE THREAD

**Issue by athamour1** [oben01/charts#69]
### Chart Name

homarr

### Chart Version

1.2.6

### Problem

I'm getting liveness-prob failures, although the service for some time is up, and it is stuck in this loop.

(in the screenshot below from lens IDE, I tried to downgrade the homarr image version to 0.15.3, but nothing changed)

![image](https://github.com/user-attachments/assets/181f1b47-4165-40e0-80f0-087ca697eaa6)
![image](https://github.com/user-attachments/assets/5c13221f-f7ee-4b57-b9cf-82d3ec30ebb6)

### values.yaml

```yaml
image:
  tag: "0.15.4"
env:
  TZ: "Europe/Athens"
imagePullSecrets:
- name: regcred
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
  # Add any additional annotations as needed
  hosts:
    - host: homarr.d2-services.home.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "homarr.d2-services.home.local"
persistence:
- name: homarr-config
  enabled: true
  storageClassName: "vsphere-csi-sc"
  accessMode: "ReadWriteOnce"
  size: "512Mi"
  mountPath: "/app/data/configs"
- name: homarr-database
  enabled: true
  storageClassName: "vsphere-csi-sc"
  accessMode: "ReadWriteOnce"
  size: "512Mi"
  mountPath: "/app/database"
- name: homarr-icons
  enabled: true
  storageClassName: "vsphere-csi-sc"
  accessMode: "ReadWriteOnce"
  size: "512Mi"
  mountPath: "/app/public/icons"
```

### Relevant log output

```shell
Exporting hostname...
Migrating database...
yarn run v1.22.19
$ ts-node ./migrate.ts
Done in 9.56s.
Starting production server...
Listening on port 7575 url: http://homarr-7fdf4cdfbb-wml77:7575
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
ℹ Database is writeable
ℹ Database is writeable
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
```
